{{- if .Values.persistence.hostPath.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "photopia.fullname" . }}-pv
  labels:
    {{- include "photopia.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain # Or Delete, depending on your needs. Retain is safer for hostPath.
  storageClassName: {{ default "" .Values.persistence.storageClassName }} # Must match PVC's storageClassName if specified
  hostPath:
    path: {{ .Values.persistence.hostPath.path }}
    type: DirectoryOrCreate # Ensures the directory exists
{{- end -}}
