apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photopia.fullname" . }}-pvc
  labels:
    {{- include "photopia.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
